/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the LICENSE file, which can be found at the root of the source code       *
 * distribution tree, or in https://www.hdfgroup.org/licenses.               *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#include "H5private.h"

H5_WARN_LARGE_STACK_OBJECTS_OFF

const char H5build_settings[]=
    "       SUMMARY OF THE HDF5 CONFIGURATION\n"
    "       =================================\n"
    "\n"
    "General Information:\n"
    "-------------------\n"
    "                   HDF5 Version: 2.0.0\n"
    "                  Configured on: 2025-12-16\n"
    "                  Configured by: Visual Studio 17 2022\n"
    "                    Host system: Windows-10.0.26100\n"
    "              Uname information: Windows\n"
    "                       Byte sex: \n"
    "             Installation point: C:/Program Files/HDF_Group/HDF5/2.0.0\n"
    "\n"
    "Compiling Options:\n"
    "------------------\n"
    "                     Build Mode: $<CONFIG>\n"
    "              Debugging Symbols: OFF\n"
    "                        Asserts: OFF\n"
    "                      Profiling: OFF\n"
    "             Optimization Level: OFF\n"
    "\n"
    "Linking Options:\n"
    "----------------\n"
    "                      Libraries: \n"
    "  Statically Linked Executables: OFF\n"
    "                        LDFLAGS: /machine:x64\n"
    "                     H5_LDFLAGS: \n"
    "                     AM_LDFLAGS: \n"
    "                Extra libraries: Threads::Threads\n"
    "                       Archiver: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64/lib.exe\n"
    "                       AR_FLAGS: \n"
    "                         Ranlib: :\n"
    "\n"
    "Languages:\n"
    "----------\n"
    "                              C: YES\n"
    "                     C Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64/cl.exe 19.44.35215.0\n"
    "                       CPPFLAGS: \n"
    "                    H5_CPPFLAGS: \n"
    "                    AM_CPPFLAGS: \n"
    "                        C Flags:  -std:c11 /DWIN32 /D_WINDOWS -wd5105 \n"
    "                     H5 C Flags: /W3;/wd4100;/wd4706;/wd4127\n"
    "                     AM C Flags: \n"
    "               Shared C Library: YES\n"
    "               Static C Library: YES\n"
    "\n"
    "\n"
    "                        Fortran: OFF\n"
    "               Fortran Compiler:  \n"
    "                  Fortran Flags:  \n"
    "               H5 Fortran Flags: \n"
    "               AM Fortran Flags: \n"
    "         Shared Fortran Library: YES\n"
    "         Static Fortran Library: YES\n"
    "               Module Directory: D:/3rd/hdf5-hdf5_2.0.0/build/mod\n"
    "\n"
    "                            C++: OFF\n"
    "                   C++ Compiler:  \n"
    "                      C++ Flags:  \n"
    "                   H5 C++ Flags: \n"
    "                   AM C++ Flags: \n"
    "             Shared C++ Library: YES\n"
    "             Static C++ Library: YES\n"
    "\n"
    "                           Java: OFF\n"
    "                  Java Compiler:  \n"
    "\n"
    "\n"
    "Features:\n"
    "---------\n"
    "                     Parallel HDF5: OFF\n"
    "  Parallel Filtered Dataset Writes: \n"
    "                Large Parallel I/O: \n"
    "                High-level library: ON\n"
    "Dimension scales w/ new references: \n"
    "                  Build HDF5 Tests: ON\n"
    "                  Build HDF5 Tools: ON\n"
    "                      Threadsafety: OFF\n"
    "                       Concurrency: OFF\n"
    "               Default API mapping: v200\n"
    "    With deprecated public symbols: ON\n"
    "            I/O filters (external): \n"
    "                  _Float16 support: OFF\n"
    "                     Map (H5M) API: \n"
    "                        Direct VFD: \n"
    "                        Mirror VFD: \n"
    "                     Subfiling VFD: \n"
    "                (Read-Only) S3 VFD: \n"
    "              (Read-Only) HDFS VFD: \n"
    "    Packages w/ extra debug output: \n"
    "                       API tracing: OFF\n"
    "              Using memory checker: OFF\n"
    "                  Use file locking: best-effort\n"
    "         Strict file format checks: OFF\n"
    "      Optimization instrumentation: \n"
;

H5_WARN_LARGE_STACK_OBJECTS_ON
